### PR TITLE
Move from Azure to GHA

### PR DESCRIPTION
**Pull request by lafrech**
This is something I've been willing to do for a while.

Now would be a good time. We have issues in Azure due to ubuntu-18.04 brownout. Fixing this would require an update to @sloria's Azure template (see https://github.com/sloria/azure-pipeline-templates/issues/5).

Switching to GHA seems like an easier move.

### CODE REVIEW

**Comment by lafrech** [comment]
@sloria, if we go this route, we need to

- remove Azure hook (not sure I can do that)
- provide PyPI API_KEY

Could you please do that?

Thanks.

**Review by sloria — APPROVED** [review]
thanks! i've added the `PYPI_API_KEY` secret and removed the AP branch protection. I'll go ahead and merge this and add the GHA branch protection.

**Comment by lafrech** [comment]
Thanks. Not sure what you mean by GHA branch protection.

Did you also change Azure config to remove the hook? I'd need the same in marshmallow-sqlalchemy. I don't think I can do it, can I?

**Comment by sloria** [comment]
There was a branch protection rule that prevented merging until the AP builds were passing. I changed that to the GHA builds

**Comment by sloria** [comment]
I think you have the privs to do marshmallow-sqlachemy now. You might need to accept the email invite for pypi

**Comment by lafrech** [comment]
I do, thanks.

I thought there might be something to do in Azure itself to disable the CI hook.

**Pull request merged**
