### PR TITLE
Schema.py - only respects exclude

### PR DESCRIPTION
**Pull request by lustdante**
I did make an issue a week ago but couldn't resist to try out this pull request.

### CODE REVIEW

**Comment by sloria** [comment]
Thanks @lustdante for tackling this.

I think the `only` parameter should still be respected, but `exclude` should also be respected. The final fields used should be the set difference between `only` and `exclude`. Could you please update your PR accordingly?

**Comment by lustdante** [comment]
Hmm, my PR was about removing self.only's short-circuiting so that it goes through field_names = field_names - excludes just like any other conditions do. I tried it on my forked repo and it's quite functional. Please let me know if any more change is required.

Thanks!

**Comment by sloria** [comment]
@lustdante Ok thanks. I will give this a closer look within the next few days.

**Comment by sloria** [comment]
This looks good. :+1: The failing test can be removed as it is no longer correct. It would be great to expand the tests to account for this API change; would you like to add those? If not, I can certainly add them when I merge.

**Comment by sloria** [comment]
Went ahead and fixed the tests. Thanks @lustdante for the fix!

**Pull request merged**
