### PR TITLE
Custom loader and dumper for field.Dict

### PR DESCRIPTION
**Pull request by sayanarijit**
Issue: #1092 

Below params added to fields.Dict

    :param type loader: The loader to use for loading objects. Defaults to dict
    :param type dumper: The dumper to use for dumping objects. Defaults to dict

### CODE REVIEW

**Comment by sloria** [comment]
Thanks for the PR.

I'm lukewarm on this because of the added API surface as well as the possible performance regression (due to an intermediate list being created). I wonder if we could expose dict creation via a method hook 🤔 .

Not going to merge this immediately, while we think of alternative approaches..

**Comment by sayanarijit** [comment]
Hi @sloria 
Thanks for considering this. I think performance concerns should be solved by 2nd commit.
If it is added, it will help with use cases [like this](https://github.com/rapidstack/RESTEasyCLI/blob/master/resteasycli/schema/common.py#L7) where ordering is critical to maintain.

**Comment by sloria** [comment]
We generally prefer separate field classes over parameters for (de)serializing to different types, i.e. `OrderedDict` > `Dict(loader=OrderedDict)`. Also, is there a need for the "load" type to be different from the "dump" type? I'm wondering if we should make the API similar to `Number`, with a `dict_type` class variable.

**Comment by sayanarijit** [comment]
This is also a good idea. Right now I cant's think of a reason of separating loader and dumper. However, as it will be parent field for all dict types, and serve as a generic field for customized needs, maybe we can let it be a little more flexible. I don't know, maybe we can have a single dict_type field also to go with the convention as no other field is using separate loader and dumper.

**Comment by sayanarijit** [comment]
Have a look at #1095

**Pull request closed without merging**
