### PR TITLE
Restore Schema.TYPE_MAPPING

### LINKED ISSUE #1012: Put TYPE_MAPPING back in Shema
It was pulled away with the inference feature.

https://github.com/marshmallow-code/marshmallow/pull/810#issuecomment-431284692

### PR DESCRIPTION
**Pull request by sloria**
close #1012

### CODE REVIEW

**Comment by lafrech** [comment]
LGTM. If it fixes environs, then go ahead and merge.

**Comment by cancan101** [comment]
Great! Any chance to get a new beta release with this fix?

**Comment by sloria** [comment]
Yeah, I'll merge and release this later today if I get time.

**Comment by sloria** [comment]
This was released in 3.0.0b19.

**Pull request merged**
