### PR TITLE
Fixes #908: Nested field default unknown to RAISE

### LINKED ISSUE #908: RAISE should be default for Nested()
Isn't it a bit weird that `Schema` defaults to `RAISE` but `Nested` defaults to `EXCLUDE`?

It's probably not what one expects (at least I didn't). How about changing the default? Or what might be the reasoning?

### PR DESCRIPTION
**Pull request by tuukkamustonen**
Ref #908.

Do we want more tests? I now just updated tests to stick with `EXCLUDE`, where necessary.

### CODE REVIEW

**Comment by sloria** [comment]
It might be good to have a test for the default behavior. Perhaps the existing tests should be updated to pass with `RAISE` instead of changing `unknown` to `EXCLUDE`?

**Comment by tuukkamustonen** [comment]
Sorry for late response. All the tests that I modified are actually testing something else than the unknown keyword validation (`@schema_validates` decorator, deserialization, ``dump_only``/``load_only``) so that's why I left their behavior as was.

Of course, it would be best to test them with combination of all ``unknown`` options (where it makes sense). I'll try to find where the generic ``Nested``/``unknown`` tests are and update/add there.

While updating the tests I bumped into https://github.com/marshmallow-code/marshmallow/issues/875#issuecomment-412347945, you may want to check it.

**Comment by lafrech** [comment]
+1 @tuukkamustonen

In https://github.com/marshmallow-code/marshmallow/pull/872, I also passed `unknown=EXCLUDE` in most tests for the same reason as they are meant to test something else.

Indeed, one test with all three values would be nice.

**Comment by sloria** [comment]
@tuukkamustonen Do you have time to update the tests?

**Comment by tuukkamustonen** [comment]
Yeah, sorry. I got a bit stuck elsewhere :)

Anyway, will do and ping then.

**Comment by tuukkamustonen** [comment]
@sloria Added `test_unknown_validation` in `test_schema.py`, to test the combinations.

It ruthlessly exceeds 80 char limit (because it's test data, not code). Is that a problem?

I didn't touch other tests (due to reasoning I wrote earlier).

**Comment by tuukkamustonen** [comment]
> It ruthlessly exceeds 80 char limit (because it's test data, not code). Is that a problem?

Flake8 test failed so I think that's a yes :D I'll fix.

(Does running flake8 on test code make sense? I always include tests, because you want to sometimes bend the rules there for flexibility.)

**Comment by tuukkamustonen** [comment]
Ok, should be good now.

**Comment by lafrech** [comment]
We do intend to flake8 the tests. flake8 enforce a set of rules that are not too restrictive.

I agree that some pylint default rules are difficult to respect in the tests and irrelevant: function names, number of variables,... But flake8 is easy to please.

Note that in marshmallow, the max length is set to 100 in [setup.cfg](https://github.com/marshmallow-code/marshmallow/blob/dev/setup.cfg).

**Comment by lafrech** [comment]
Thanks for that new test.

Was the grandchild necessary to test `Nested`? AFAIU, the test on the first level should be enough.

**Comment by tuukkamustonen** [comment]
> Was the grandchild necessary to test Nested? AFAIU, the test on the first level should be enough.

Not really, but I assumed you'd rather want it than not. Anyway, I can simplify it, if you want?

What I mean is that I don't know the library that well, so I thought it might reveal something and ended up adding grand child to the test. Well, it didn't reveal anything but I left it there anyhow.

**Comment by lafrech** [comment]
Yeah, I understand. It tend to do that as well.

As the tests are piling up, it is nice to keep them as focused as possible, to make them clear about their intent, and to avoid complexifying refactors unnecessarily.

Thanks for your work already. If you have time, you may simplify it, it'll be appreciated. Otherwise, I can try to find some time to do it later, even after this is merged.

Also, please rename the test as `test_nested_unknown_validation`.

Thanks again.

**Comment by tuukkamustonen** [comment]
@lafrech Sorry again, I've been afk. I'll simplify the test.

About naming though: it's already member of `TestNestedSchema` class, that's why I left "nested" away from method name. But yeah, I see all the other methods have "nested" in their name so I'll add it.

**Comment by lafrech** [comment]
No pb.

I think the rationale about the naming is that you may want to run 

    py.test -k my_test_function

I can't tell for marshmallow, but in my application tests, I write long function names including all the hierarchy (like `test_module_class_function_behaviour`) to avoid duplicate function names and let `-k` be more selective.

**Comment by tuukkamustonen** [comment]
Good to know about `-k` conventions - I just normally run tests within IDE and rarely need selective runs on command-line.

Anyway, pushed the changes.

Edit: Resolved conflicts.

**Comment by lafrech** [comment]
Looks good to me. Thanks!

**Pull request merged**
