### PR TITLE
Remove Number.serialize and check as_string in Number._serialize

### LINKED ISSUE #788: fields.List of fields.Integer doesn't work as expected with as_string
Currently this does not seem correct:

```
>>> o = type('Object', (), {'ids': [1,2,3]})()
>>> field = fields.List(fields.Integer(as_string=True))
>>> field.serialize('ids', o)
[1, 2, 3]
```

I was expecting `['1', '2', '3']`

It does work as expected for single values:

```
>>> o = type('Object', (), {'id': 1})()
>>> single_field = fields.Integer(as_string=True)
>>> single_field.serialize('id', o)
'1'
```

### PR DESCRIPTION
**Pull request by lafrech**
Fixes #788.

### CODE REVIEW

**Comment by lafrech** [comment]
There is a design issue behind this. The fact that `List` calls `container._serialize` means that for each `field`, everything should happen in there and overriding `serialize` in a `field` is smelly.

Should we state this explicitly somewhere?

I don't think it makes sense to add a test for this specific use case, or we might as well add equivalent tests for all features of all fields (test that each feature works when used inside a `List` field).

Should we test that each field does not override `serialize`? This would be easy to do, but it sounds bad.

**Comment by deckar01** [comment]
I think the underlying issue here is that `Field` is being given the responsibility of accessing schema level objects and plucking its own data out. That seems like it should be the responsibility of the schema or the marshaller. The only place that `serialize` is used internally is in `Marshaller.serialize`.

Maybe we should move the plucking+serializing logic to `marshaller.serialize_field`?

**Comment by lafrech** [comment]
This makes sense. Same for `deserialize`.

This goes much further than this PR, though.

I'm open to rework suggestions on this PR but I think this is the right thing to do and it should be done on 2.x as bugifx. Hence https://github.com/marshmallow-code/marshmallow/pull/790.

Then in `dev` branch, we can try to implement the change you suggest for MA3. Would you like to open an issue about it?

**Comment by deckar01** [comment]
I opened #799 to discuss refactoring serialize.

**Comment by lafrech** [comment]
Applied to `2.x` (https://github.com/marshmallow-code/marshmallow/pull/789) then merged into `dev`.

**Pull request closed without merging**
