### PR TITLE
Use type hints made available in Python 3.9 and 3.10.

### PR DESCRIPTION
**Pull request by Isira-Seneviratne**

### CODE REVIEW

**Review by lafrech — APPROVED** [review]
Looks god to me. Thank you so much.

Let's merge #1923 first.

**Comment by lafrech** [comment]
@sloria, I'd like to merge this. Any objection?

**Comment by sloria** [comment]
Go for it!

**Comment by lafrech** [comment]
The tests failed on Python 3.7. There must be something I'm missing, here. I did check the docs and I thought the feature used here was introduced in Python 3.7 (https://docs.python.org/3/whatsnew/3.7.html#pep-563-postponed-evaluation-of-annotations).

I reverted the merge in dev branch for now. @Isira-Seneviratne do you mind rebasing and fixing?

Also, the docs read

> It will become the default in Python 3.10.

so my understanding is that the feature is introduced in 3.7 through `__future__.annotations`  and default in 3.10 (no need to import `__future__.annotations` from 3.10 on). I don't understand the reference to 3.9 in the commit / PR title.

I should have asked for a rebase before merging, but no big deal.

**Comment by Isira-Seneviratne** [comment]
> The tests failed on Python 3.7. There must be something I'm missing, here. I did check the docs and I thought the feature used here was introduced in Python 3.7 (https://docs.python.org/3/whatsnew/3.7.html#pep-563-postponed-evaluation-of-annotations).
> 
> I reverted the merge in dev branch for now. @Isira-Seneviratne do you mind rebasing and fixing?
> 
No, I can do it.

**Pull request merged**
