### PR TITLE
Adding load support for only=basestring for Nested field

### PR DESCRIPTION
**Pull request by erlingbo**
Proposal for solving #307

### CODE REVIEW

**Comment by sloria** [comment]
Thanks for the PR @erlingbo . I see the rationale for this change. This could, however, break backwards compatibility, so we'll have to consider whether the benefits are worth that cost. I'll have to think about this.

**Comment by ghost** [comment]
I would like also to have this feature. 

It's most readable, JSON becomes most light and you manage the relationship in the server.

Choice 1:
`{
  "country": {
    "country_id": 1,
    "country": "France",
    "country_code": "FR"
  }
}
`
Choice 2:
`{
  "country": "FR"
}`

**Comment by deckar01** [comment]
Serialization and deserialization should be symmetric operations. The fact that the `NestedField` serialization logic handles the `only` property, but the deserialization logic does not indicates that the implementation is asymmetric.

Deserializing data that Marshmallow itself created currently results in an error. Considering that the documentation only describes how the `only` option affects serialization, deserialization of a `Nested` field with the `only` option supplied as a string should be consider undocumented behavior.

I would argue that it can reasonably be assumed that serialization and deserialization are symmetric, therefore this change would be considered a bug fix warranting a patch bump. I can see an argument that defining undefined behavior could be considered a feature warranting a minor version bump. I would not consider this a breaking change.

I would suggest documenting the deserialization behavior in this PR:

``` py
        :emphasize-lines: 4, 11, 18

        class UserSchema(Schema):
            name = fields.String()
            email = fields.Email()
            friends = fields.Nested('self', only='name', many=True)
        # ... create ``user`` ...
        result, errors = UserSchema().dump(user)
        pprint(result)
        # {
        #     "name": "Steve",
        #     "email": "steve@example.com",
        #     "friends": ["Mike", "Joe"]
        # }
        data = UserSchema().load(result)
        pprint(data)
        # {
        #     "name": "Steve",
        #     "email": "steve@example.com",
        #     "friends": [{"name": "Mike"}, {"name": "Joe"}]
        # }
```

[docs/nesting.rst#L90](https://github.com/marshmallow-code/marshmallow/blob/d35151/docs/nesting.rst#L90)

**Comment by sloria** [comment]
Let's move this forward for 3.0.0. All that's left to do is add documentation. I like @deckar01 's suggestion above.

@erlingbo Feel free to make the update (and add yourself to AUTHORS). Otherwise, I'll try to get to this over the weekend.

**Comment by sloria** [comment]
This has been rebased and merged into `dev`. Thanks @erlingbo for the PR!

**Pull request closed without merging**
