### PR TITLE
fix `Eqaul(False)` cant validate correctly

### PR DESCRIPTION
**Pull request by pktangyue**
#484

### CODE REVIEW

**Comment by deckar01** [comment]
It looks like this PR would cause a false positives for a custom validator that returns `False` instead of raising a `ValidationError`.

> Validation functions either return a boolean or raise a ValidationError.

https://marshmallow.readthedocs.io/en/latest/quickstart.html#validation

It looks like the built in validators should not be returning the value.

**Comment by pktangyue** [comment]
@deckar01 Yes, I agree with you.
At the first, I change `__call__` method of `Eqaul` to:

``` python
def __call__(self, value):
  if value != self.comparable:
    raise ValidationError(self._format_error(value))
  return True
```

But I found this change can't pass the test, like `assert validate.Equal('a')('a') == 'a'`.

I couldn't find out why these built in validators return the value.

Maybe I could change all built in validators to return False/True, as well the tests?

**Comment by deckar01** [comment]
I don't think that the validators need to return anything since they already raise an error.

> **either** return a boolean **or** raise a ValidationError. (emphasis added)

Raising an exception implicitly causes the test to fail, so no `assert` would be required.

Thanks for working on this @pktangyue.

**Comment by sloria** [comment]
This bug is fixed in a simpler way in #527.

**Pull request closed without merging**
