### PR TITLE
Accept dict in messages errors

### PR DESCRIPTION
**Pull request by DanielBacci**
Hi,
I had a problem for return the fields with errors. My api should follow:

`field_name = [{"code": 4001, "message": "error desc" }]`

I like solution for required fields http://marshmallow.readthedocs.org/en/latest/quickstart.html,
 `city = fields.String(required={'message': 'City required', 'code': 400})`, but not working to validate :(.

My solution to problem is this PR, but accept suggestions.

Thanks :)

### CODE REVIEW

**Comment by danielbacci-luizalabs** [comment]
cc @sloria @justanr

Can you review please ?

**Comment by sloria** [comment]
Passing a dictionary or string as the `required` argument was removed from the API (https://marshmallow.readthedocs.org/en/latest/changelog.html#id14). I've just update the documentation in the Quickstart accordingly. 

In your code, you would do:

``` python
city = fields.String(required=True, error_messages={'required': {'message': 'City required', 'code': 400}})
```

Does that meet your use case?

**Comment by danielbacci-luizalabs** [comment]
@sloria it works for required fields, but in my case i need pass a dictionary or string to validate like Length or Regexp ...

Example:

`zipcode = fields.Str(
        required=True,
        error_messages={"required": {"message": "message error", "code": "code error"}},
        validate=[
            validate.Length(max=8, error={"message": "message error", "code", "code error"})])`

**Comment by sloria** [comment]
OK, it does make sense to allow the `error` parameter for validators to be a dictionary, though I'm unsure that this PR takes the right approach. The special-casing of the `message` name feels off to me.

**Comment by sloria** [comment]
Closing this for now; feel free to reopen if you think there's still a need for this.

**Pull request closed without merging**
