### PR TITLE
Fix #772 Empty Only Treated as None

### LINKED ISSUE #535: How is deserialization affected by only and partial?
I was hoping to get some clarification on the differences between `only` and `partial` with respect to deserialization. (This question is similar to #509 which addresses serialization using the same fields.) Based on the docs and the response to that issue, I interpreted it to mean that `only` applies to serialization and `partial` applies to deserialization. However, in testing it looks like `only` also affects deserialization. What am I missing?

``` python
from marshmallow import Schema, fields

class MySchema(Schema):
    foo = fields.Field(required=True)
    bar = fields.Field(required=True)

only_schema = MySchema(only=('foo', ))
partial_schema = MySchema(partial=True)

print(only_schema.load({'foo': 42, 'bar': 24}))
print(only_schema.load({'foo': 42}))
print(partial_schema.load({'foo': 42, 'bar': 24}))
print(partial_schema.load({'foo': 42}))
```

Output:

``` python
UnmarshalResult(data={u'foo': 42}, errors={})
UnmarshalResult(data={u'foo': 42}, errors={})
UnmarshalResult(data={'foo': 42, 'bar': 24}, errors={})
UnmarshalResult(data={'foo': 42}, errors={})
```

I expected deserialization using `only_schema` to result in an error similar to the example below. 

``` python
MySchema().load({'foo':42})
```

Output:

``` python
UnmarshalResult(data={'foo': 42}, errors={'bar': [u'Missing data for required field.']})
```

Ultimately, I'm trying to get away with using the same schema for (de)serialization, but maybe that's not the ideal way to use marshmallow.

### LINKED ISSUE #772: Empty Only Treated as None
When the `only` parameter is an empty list/set, it causes all the fields to be de/serialized like `None`. The implementation of 2.x and 3.0 are not in compliance with their respective docs.

> **only** (_tuple_) – A list or tuple of fields to serialize. If **None**, all fields will be serialized.

```py
class TestSchema(Schema):
    foo = fields.Field()
sch = TestSchema(only=())
data = dict(foo='bar')
result = sch.dump(data)
assert 'foo' not in result

# assert 'foo' not in {'foo': 'bar'}
```

This could create a security vulnerability if an application was dynamically generating the field set based on security role. A filter that was meant to hide everything would inadvertently show everything.

### PR DESCRIPTION
**Pull request by lafrech**
Implementation of the fix described in https://github.com/marshmallow-code/marshmallow/issues/772#issuecomment-380975300.

I also reworded the docstring a bit (this is a rework of https://github.com/marshmallow-code/marshmallow/pull/771 which hopefully should close https://github.com/marshmallow-code/marshmallow/issues/535). I'm open to suggestions for a better wording.

### CODE REVIEW

**Comment by deckar01** [comment]
Looks good to me. Thanks @lafrech!

@sloria Should this be released in the next patch of 2.x?

**Comment by lafrech** [comment]
I don't know if we have a rule to express the `:param` types in the docstrings.

Since the text said "tuple or list" I figured I'd use `tuple|list` as type and remove this from the sentence.

But I might as well be listing all collection types... Maybe tuple was enough and the user can imagine a list will fit as well.

Later in the file, only tuple is specified:

```python
    def validate(self, data, many=None, partial=None):
        """Validate `data` against the schema, returning a dictionary of
        validation errors.
        [...]
        :param bool|tuple partial: Whether to ignore missing fields. If `None`,
            the value for `self.partial` is used. If its value is an iterable,
```

No big deal anyway. Just trying to get it right.

**Comment by sloria** [comment]
Yes, this should be sent to the 2.x-line branch. 

> Since the text said "tuple or list" I figured I'd use tuple|list as type and remove this from the sentence.

Good idea.

@lafrech Would you mind resending this to `2.x-line`?

**Comment by sloria** [comment]
Done in #782

**Pull request closed without merging**
