### PR TITLE
Add Schema.from_dict for generating schemas from dicts

### LINKED ISSUE #1312: Add a way to generate a Schema from a dictionary
Generating schemas at runtime is a fairly common use case that I've run into a handful of times at this point ([webargs](https://github.com/marshmallow-code/webargs/blob/de061e037285fd08a42d73be95bc779f2a4e3c47/src/webargs/core.py#L50-L63), [environs](https://github.com/sloria/environs/blob/91b32a0e4bdf40281fab3978368164b27ce65e39/environs.py#L83-L95) , form builders...). 

It might make sense to incorporate this into marshmallow core.

## Proposed API

```python
>>> MyDynamicSchema = Schema.from_dict({"foo": fields.Str()})
>>> MyDynamicSchema
<class 'marshmallow.schema.GeneratedSchema'>
```

```python
class AlbumSchema(Schema):
     artist = fields.Nested(Schema.from_dict({"name": fields.Str()})
```

### PR DESCRIPTION
**Pull request by sloria**
close #1312

### CODE REVIEW

**Review by lafrech — APPROVED** [review]
LGTM.

Maybe another argument could be added to pass meta options in the call to `from_dict` but it can be added later on if someone needs it.

**Comment by sloria** [comment]
I wanted to keep the API surface to a minimum here. If a user needs to customize `Meta`, they can declare a class.

**Comment by lafrech** [comment]
Note: `from_dict` only generates fields for top-level fields in the dict. It does not create `Nested` fields automatically: https://stackoverflow.com/questions/58190523/how-to-use-schema-from-dict-for-nested-dictionaries.

**Comment by sloria** [comment]
It was not the intention to automagically create `Nested` and `List` fields for dicts and lists. I don't think it's necessary nor intuitive, but I'm not closed off to the idea if others think it's the way to go.

**Comment by hardikkat24** [comment]
@sloria Wouldn't it be great for `fields.Nested()` to accept both dictionary and Schema? Thanks!

**Comment by sloria** [comment]
@hardikkat24 That can be achieved quite easily with a subclass of `Nested`. See https://github.com/marshmallow-code/webargs/blob/0357a525118acbc19bc5a1981f6161ee79110579/src/webargs/fields.py#L26-L40

**Pull request merged**
