### PR TITLE
Fix contained parent in container fields

### PR DESCRIPTION
**Pull request by lafrech**
I think this is the right fix for https://github.com/marshmallow-code/marshmallow/issues/779#issuecomment-396354987.

I had to modify some tests. Apparently, the former behaviour was intended but I don't see why so I assume it was a mistake.

### CODE REVIEW

**Comment by sloria** [comment]
I think the former behavior is actually correct. The `parent` of an inner field is the container field, while its `root` will be the schema. Can the `List(Nested('self'))` case be addressed without changing these semantics?

**Comment by lafrech** [comment]
Yep. I wasn't sure about the meaning or `parent`. Thanks for clarifying.

`root`:

> Reference to the `Schema` that this field belongs to even if it is buried in a container field (e.g. `List`).

IIUC, the proper fix is to use `root` instead of `parent` in `Nested`.

```py
                elif self.nested == "self":
-                   schema_class = self.parent.__class__
+                   schema_class = self.root.__class__
```

Looks like this bugfix should be applied to 2.x as well, right?

**Comment by sloria** [comment]
> IIUC, the proper fix is to use root instead of parent in Nested.

I don't think that will handle deep self-nesting e.g.

```python
class TreeNodeSchema():
    children = List(Nested('self'))

class MySchema(Schema):
    tree = Nested(TreeNodeSchema())
```

**Comment by sloria** [comment]
Btw, I'm tempted to deprecate `'self'` in favor of explicitly passing the schema name.

```python
class TreeNodeSchema():
    children = List(Nested('TreeNodeSchema'))
```

wdyt?

**Comment by lafrech** [comment]
I'm not sure why it wouldn't work. Is it because `root` would be `MySchema` rather than `TreeNodeSchema`?

Looking at it I remembered that I wanted to remove `root` in MA 4 so I thought "what if we just removed `self` and asked for the schema name instead"?

Therefore, +1 for removing `self`.

**Comment by sloria** [comment]
> I'm not sure why it wouldn't work. Is it because root would be MySchema rather than TreeNodeSchema?

Right.

> Therefore, +1 for removing self.

OK, let's go with this, eventually. So unless you find an easy fix for `List(Nested('self'))` that doesn't break `root`/`parent`, I think we can just document this limitation of the List(Nested) form.

**Comment by lafrech** [comment]
I suppose a fix could be to climb up `parent` hierarchy, just like when searching for `root`, but stopping at the first `SchemaABC` instance.

IIUC, your plan is to deprecate `self` in MA3 and remove it in MA4, so we'd live with this ugly fix only until MA4. Fine.

**Comment by sloria** [comment]
> I suppose a fix could be to climb up parent hierarchy, just like when searching for root, but stopping at the first SchemaABC instance.

Yes, that should work.

> IIUC, your plan is to deprecate self in MA3 and remove it in MA4, so we'd live with this ugly fix only until MA4. Fine.

Right.

**Comment by deckar01** [comment]
This change makes sense to me. `Field.parent` is supposed to be a schema, but it was being set to collection field instances. This mostly worked, because the few things that `parent` is used for are also proxied through the fields to their parent schema. The thing that broke was `Nested('self')` expecting `self.parent.__class__` to be a schema. Even if `Nested('self')` was deprecated/removed, this fix would avoid unnecessary indirection on some nested container attributes.

**Comment by sloria** [comment]
Interesting, so I think the original intention was that `parent` was the _immediate_ parent, which could be either a Field or Schema. Without doing a code dive, I'm not sure what use cases would break if we changed parent to always be the nearest ancestor Schema. I'm open to the idea if you both think it's more intuitive.

**Comment by deckar01** [comment]
I can see how allowing `parent` to point to fields might be more useful. ~~The only outlier was `Nested` pointing to its parent instead of itself.~~

I initially thought "climb up parent hierarchy" was referring to `_bind_to_schema()`, but maybe you meant just for resolving `Nested('self')`. That would work.

**Comment by sloria** [comment]
> I initially thought "climb up parent hierarchy" was referring to _bind_to_schema(), but maybe you meant just for fixing Nested('self'). That would work.

Right, we'd only do the climb-to-nearest-schema for the `'self'` use case.

**Comment by lafrech** [comment]
> Without doing a code dive, I'm not sure what use cases would break if we changed parent to always be the nearest ancestor Schema.

I think that's what this PR does and it only breaks the tests that precisely test `parent` in container fields. I didn't see any other side-effects.

It's unclear to me who/what actually uses the `parent` attribute outside of our own code. Is this something other users/libs might be relying upon?

> I can see how allowing parent to point to fields might be more useful.

I have no use case in mind.

The "climb up" patch would solve the `Nested` issue so at least we got this covered. The question about what to do about `parent` remains.

> I'm open to the idea if you both think it's more intuitive.

I have no idea. It seems clearer to you guys than it is to me.

**Comment by sloria** [comment]
On a surface level, `parent` = immediate parent makes more intuitive sense to me. Let's keep the current semantics, if only to avoid introducing an unnecessary breaking change. Then use the climb-up patch here.

**Comment by lafrech** [comment]
Replaced by https://github.com/marshmallow-code/marshmallow/pull/1294.

**Pull request closed without merging**
