### PR TITLE
Catch validation errors raised during post processing.

### PR DESCRIPTION
**Pull request by dbertouille**
Catch validation errors raised during post processing.
Moved post processing before error handling.
Added a simple test.

Issue #472

### CODE REVIEW

**Comment by sloria** [comment]
@dbertouille Could you please update this with the latest dev branch?

**Comment by dbertouille** [comment]
@sloria Ah my bad, done.

**Comment by sloria** [comment]
It would make sense to handle ValidationErrors in any of the `pre_`/`post_`-decorated methods. @dbertouille Could you update this PR to implement that behavior?

**Comment by dbertouille** [comment]
@sloria  The calls to pre/post dump/load will now catch ValidationError exceptions. Was there anything I missed?

**Comment by sloria** [comment]
Thank you for working on this @dbertouille .

There are a few lingering, potential issues:
- What should the behavior be if a string is passed to ValidationError?

``` python

class MySchema(Schema):
    foo = fields.Field()

    @pre_load
    def pre_load(self, data):
        raise ValidationError('pre_load error')

sch = MySchema()
print(sch.load({'foo': 'green'}).errors)
```

Current output with this PR: `['pre_load error']`

I'm wondering if we should instead store this on the `_schema` key, such that the output would be `{'_schema': ['pre_load error']` . Though I'm not 100% sure on this.
- Passing a field name to `ValidationError` doesn't work

In schema validators, you can pass a field name or a list of field names to store the error on in the errors dict. See http://marshmallow.readthedocs.io/en/latest/extending.html#storing-errors-on-specific-fields . This doesn't currently work in this PR:

``` python
class MySchema(Schema):
    foo = fields.Field(validate=OneOf(['red', 'blue']))

    @pre_load
    def pre_load(self, data):
        raise ValidationError('pre_load error', 'foo')

sch = MySchema()
print(sch.load({'foo': 'green'}).errors)
```

Expected output: `{'foo': ['pre_load error']}`
Actual output: `['pre_load error']`

**Comment by dbertouille** [comment]
I've had a chance to look at this again @sloria. I've updated the PR to handle those two cases.

I'm also not 100% sure that we should default the error messages key to '_schema' when nothing is supplied. The only other thing that comes to my mind is to add some other special keys. Something along the lines '_preprocess' or '_postprocess'.

**Comment by sloria** [comment]
@dbertouille Thank you for updating the PR. Looks to be behaving as expected. 👍 

I think adding to `_schema` is a fine default, since errors raised without a field name will be schema-level validation failures. If the user wants to save on a different key, they can do so:

``` python
    @pre_load
    def pre_load(self, data):
        raise ValidationError('pre_load error', '_pre_load')
```

Or even:

``` python
class PreprocessingError(ValidationError):

    def __init__(self, message, *args, **kwargs):
        field_names = kwargs.pop('field_names', '_pre_load')
        super().__init__(message, field_names=field_names, *args, **kwargs)

class MySchema(Schema):
   #...

    @pre_load
    def pre_load(self, data):
        raise PreprocessingError('pre_load error')
```

**Comment by henryfjordan** [comment]
I know this is really old, but I just ran into a subtle issue that broke some of my unit tests in a project relying on marshmallow:

This PR changes the behavior of `dump()` to now not run `@post_dump` methods if an error is encountered. While understandable (and probably more correct), this is a breaking change and probably should be noted in the changelog.

**Pull request merged**
